name: jeepboxhero
description: A record shop simulation game

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.32.0
  flame_audio: ^1.0.6
  supabase_flutter: ^2.5.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/ui/
    - assets/characters/
    - assets/shelves/
    - assets/albums/
    - assets/receipts/
    - assets/audio/