name: jeep_box_hero
description: A narrative-driven OPM vinyl shop simulation
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add your assets here:
  assets:
    - assets/albums/
    - assets/customers/
    - assets/audio/
    - assets/backgrounds/
    
  fonts:
    - family: Courier
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
